-- 1. Daily Visits Table
create table if not exists daily_visits (
  id bigint generated by default as identity primary key,
  date date not null unique default current_date,
  count int not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RPC to increment daily visit count
create or replace function increment_visit()
returns void
language plpgsql
security definer
as $$
begin
  insert into daily_visits (date, count)
  values (current_date, 1)
  on conflict (date)
  do update set count = daily_visits.count + 1;
end;
$$;

-- 3. RPC to increment article view count
create or replace function increment_article_view(article_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  update articles
  set views = views + 1
  where id = article_id;
end;
$$;

-- 4. Enable RLS on daily_visits (optional but good practice)
alter table daily_visits enable row level security;

-- Allow anon to insert/update (via RPC is safer, but for now we grant access)
grant select, insert, update on daily_visits to anon;
grant select, insert, update on daily_visits to authenticated;
grant select, insert, update on daily_visits to service_role;
